"""
Django settings for clarify project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

from pathlib import Path
from django.contrib.messages import constants as messages
from dotenv import load_dotenv
import os
import sys

load_dotenv()

# Label the environment we are in.
# This is set up for PythonAnywhere deployment and must change if the
# deployment platform changes.
if "test" in sys.argv:
    ENVIRONMENT = "test"
elif "PYTHONANYWHERE_SITE" in os.environ:
    ENVIRONMENT = "production"
else:
    ENVIRONMENT = "development"

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
if ENVIRONMENT == "production":
    SECRET_KEY = str(os.getenv("SECRET_KEY"))
else:
    SECRET_KEY = "django-insecure-n*%ityrpt9+wxz#e%i(&7_1e=w-dv1h33&$n(mg=$0&8m0k5f-"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = ENVIRONMENT == "development"

ALLOWED_HOSTS = ["clarify.pythonanywhere.com", "localhost", "127.0.0.1"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "widget_tweaks",
    "tickets",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "clarify.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "clarify.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": BASE_DIR / "db.sqlite3",
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"
STATIC_ROOT = "assets/"
STATICFILES_DIRS = [
    BASE_DIR / "static",
]

# Media files
MEDIA_URL = "media/"
MEDIA_ROOT = BASE_DIR / "media"

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# User model for authentication and login purposes
AUTH_USER_MODEL = "tickets.User"

# Login URL for redirecting users from login protected views
LOGIN_URL = "log_in"

# URL where @login_prohibited redirects to
REDIRECT_URL_WHEN_LOGGED_IN = "dashboard"

# Convert Django ERROR messages to Bootstrap DANGER messages
MESSAGE_TAGS = {
    messages.ERROR: "danger",
}

# Security settings
if ENVIRONMENT == "production":
    SECURE_HSTS_SECONDS = 3600
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_PRELOAD = True

# Pagination settings
ITEMS_PER_PAGE = 20

# File extensions settings
ALLOWED_EXTENSIONS = ["pdf", "doc", "docx", "txt", "jpg", "jpeg", "png"]
ALLOWED_EXTENSIONS_ACCEPT = ",".join(f".{e}" for e in ALLOWED_EXTENSIONS)
ALLOWED_EXTENSIONS_LABEL = (
    "Attachments (max 5 files, 5MB each — pdf, doc, docx, txt, jpg, jpeg, png)"
)

# Comment settings
EDIT_TIME_LIMIT_MINUTES = 10

# Body length max for text fields
BODY_LENGTH_MAX = 50000

# CRON settings
CRON_TOKEN = os.environ.get("CRON_TOKEN", "")

# Base URL for links in emails
SITE_URL = os.getenv("SITE_URL", "http://localhost:8000")

# Email (SMTP) configuration
EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = os.getenv("EMAIL_HOST", "smtp.gmail.com")
EMAIL_PORT = int(os.getenv("EMAIL_PORT", "587"))
EMAIL_USE_TLS = os.getenv("EMAIL_USE_TLS", "True") == "True"
EMAIL_HOST_USER = os.getenv("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = os.getenv("EMAIL_HOST_PASSWORD", "")
DEFAULT_FROM_EMAIL = os.getenv("DEFAULT_FROM_EMAIL", EMAIL_HOST_USER)

# IMAP configuration (for reading incoming emails)
IMAP_HOST = os.getenv("IMAP_HOST", "imap.gmail.com")
IMAP_PORT = int(os.getenv("IMAP_PORT", "993"))
IMAP_USER = os.getenv("IMAP_USER", "") or EMAIL_HOST_USER
IMAP_PASSWORD = os.getenv("IMAP_PASSWORD", "") or EMAIL_HOST_PASSWORD

if "test" in sys.argv:
    EMAIL_HOST_USER = ""
    EMAIL_HOST_PASSWORD = ""
    DEFAULT_FROM_EMAIL = ""

# Ticket email templates (override via env if needed)
TICKET_CREATED_EMAIL_SUBJECT = os.getenv(
    "TICKET_CREATED_EMAIL_SUBJECT",
    "We received your query (Ticket #{ticket_id})",
)
TICKET_CREATED_EMAIL_BODY = os.getenv(
    "TICKET_CREATED_EMAIL_BODY",
    (
        "Dear {first_name},\n\n"
        "Your ticket has been received. We'll review it and get back to you.\n\n"
        "Ticket ID: {ticket_id}\n"
        "Subject: {subject}\n\n"
        "Thanks,\n"
        "Clarify Team"
    ),
)
