"""User fixtures for the seed."""

from tickets.models import User, Ticket

user_fixtures = [
    {
        "username": "@johndoe",
        "email": "john.doe@example.org",
        "first_name": "John",
        "last_name": "Doe",
        "preferred_name": "John",
        "pronouns": "he/him",
        "user_type": User.USER_TYPE_STUDENT,
        "student_id": "12345678",
        "phone_number": "+44 0000 000001",
        "faculty": Ticket.Faculty.FOLSM,
        "study_level": Ticket.StudyLevel.UNDERGRADUATE,
        "graduation_year": 2027,
    },
    {
        "username": "@janedoe",
        "email": "jane.doe@example.org",
        "first_name": "Jane",
        "last_name": "Doe",
        "preferred_name": "Jane",
        "pronouns": "she/her",
        "user_type": User.USER_TYPE_STUDENT,
        "student_id": "12345679",
        "phone_number": "+44 0000 000002",
        "faculty": Ticket.Faculty.SSPP,
        "study_level": Ticket.StudyLevel.POSTGRADUATE_TAUGHT,
        "graduation_year": 2026,
    },
    {
        "username": "@charlie",
        "email": "charlie.johnson@example.org",
        "first_name": "Charlie",
        "last_name": "Johnson",
        "preferred_name": "Charlie",
        "pronouns": "they/them",
        "user_type": User.USER_TYPE_STUDENT,
        "student_id": "12345681",
        "phone_number": "+44 7000 000003",
        "faculty": Ticket.Faculty.NMES,
        "study_level": Ticket.StudyLevel.UNDERGRADUATE,
        "graduation_year": 2028,
    },
    {
        "username": "@student001",
        "email": "student001@example.org",
        "first_name": "Student",
        "last_name": "001",
        "preferred_name": "Hercules",
        "pronouns": "he/him",
        "user_type": User.USER_TYPE_STUDENT,
        "student_id": "12345682",
        "phone_number": "",
        "faculty": Ticket.Faculty.KBS,
        "study_level": Ticket.StudyLevel.POSTGRADUATE_RESEARCH,
        "graduation_year": 2029,
    },
    {
        "username": "@staff001",
        "email": "staff001@example.org",
        "first_name": "Staff",
        "last_name": "001",
        "preferred_name": "Steve",
        "pronouns": "he/him",
        "user_type": User.USER_TYPE_STAFF,
    },
    {
        "username": "@staff002",
        "email": "staff002@example.org",
        "first_name": "Staff",
        "last_name": "002",
        "preferred_name": "Alex",
        "pronouns": "she/her",
        "user_type": User.USER_TYPE_STAFF,
    },
    {
        "username": "@admin",
        "email": "admin@example.org",
        "first_name": "Admin",
        "last_name": "User",
        "preferred_name": "Remy",
        "pronouns": "they/them",
        "user_type": User.USER_TYPE_STAFF,
        "is_superuser": True,
        "is_staff": True,
    },
]
