"""Keyword mappings for classifying emails into ticket fields."""

FACULTY_KEYWORDS = {
    "folsm": [
        "life sciences",
        "medicine",
        "biomedical",
        "biology",
        "pharmacy",
        "folsm",
    ],
    "sspp": [
        "social science",
        "public policy",
        "politics",
        "international relations",
        "sociology",
        "education",
        "sspp",
    ],
    "nmpc": [
        "nursing",
        "midwifery",
        "palliative care",
        "nmpc",
        "nightingale",
    ],
    "nmes": [
        "engineering",
        "mathematics",
        "physics",
        "computer science",
        "chemistry",
        "informatics",
        "nmes",
        "natural sciences",
    ],
    "ah": [
        "arts",
        "humanities",
        "english",
        "history",
        "philosophy",
        "music",
        "film",
        "classics",
        "languages",
        "liberal arts",
    ],
    "kbs": [
        "business",
        "management",
        "accounting",
        "finance",
        "marketing",
        "economics",
        "kbs",
    ],
    "docs": [
        "dentistry",
        "oral",
        "craniofacial",
        "dental",
    ],
    "dpsol": [
        "law",
        "legal",
        "dickson poon",
        "dpsol",
    ],
    "ioppn": [
        "psychiatry",
        "psychology",
        "neuroscience",
        "mental health",
        "ioppn",
    ],
}

STUDY_LEVEL_KEYWORDS = {
    "undergraduate": [
        "undergraduate",
        "undergrad",
        "bachelors",
        "bachelor",
        "bsc",
        "ba",
        "first year",
        "second year",
        "third year",
        "final year",
    ],
    "postgraduate_taught": [
        "postgraduate taught",
        "masters",
        "msc",
        "ma",
        "mba",
        "pgce",
        "taught postgraduate",
        "taught masters",
    ],
    "postgraduate_research": [
        "postgraduate research",
        "phd",
        "doctoral",
        "doctorate",
        "research degree",
        "mphil",
        "dphil",
    ],
    "other": [
        "foundation",
        "exchange",
        "visiting",
        "distance learning",
    ],
}

CATEGORY_KEYWORDS = {
    "assessment": [
        "assessment",
        "exam",
        "examination",
        "coursework",
        "assignment",
        "grade",
        "grading",
        "marks",
        "results",
        "deadline",
        "submission",
        "essay",
        "dissertation",
        "thesis",
    ],
    "welfare": [
        "welfare",
        "personal issues",
        "support",
        "counselling",
        "counseling",
        "pastoral",
    ],
    "careers": [
        "careers",
        "career",
        "employment",
        "internship",
        "placement",
        "job",
        "cv",
        "interview",
        "graduate scheme",
    ],
    "financial_issues": [
        "financial",
        "money",
        "bursary",
        "scholarship",
        "hardship",
        "tuition",
    ],
    "uni_procedures_regulations": [
        "procedures",
        "regulations",
        "policy",
        "rules",
        "academic regulations",
        "extenuating circumstances",
        "mitigating",
    ],
    "administration": [
        "administration",
        "admin",
        "enrolment",
        "enrollment",
        "registration",
        "transcript",
        "certificate",
        "timetable",
    ],
    "appeals_complaints_and_misconduct": [
        "appeal",
        "complaint",
        "misconduct",
        "plagiarism",
        "academic integrity",
        "disciplinary",
    ],
    "dignity_and_inclusion": [
        "dignity",
        "inclusion",
        "discrimination",
        "harassment",
        "equality",
        "diversity",
        "bullying",
    ],
    "disability_support": [
        "disability",
        "disabled",
        "accessibility",
        "reasonable adjustment",
        "learning difference",
        "dyslexia",
        "adhd",
    ],
    "document_and_letter_requests": [
        "document request",
        "letter request",
        "reference letter",
        "confirmation letter",
        "enrollment letter",
        "proof of study",
    ],
    "fees_funding_and_money_advice": [
        "fees",
        "funding",
        "student loan",
        "student finance",
        "money advice",
        "payment plan",
    ],
    "graduation": [
        "graduation",
        "ceremony",
        "degree certificate",
        "graduating",
        "convocation",
    ],
    "health_and_wellbeing": [
        "health",
        "wellbeing",
        "well-being",
        "mental health",
        "doctor",
        "medical",
        "illness",
        "sick",
    ],
    "housing_and_accommodation_support": [
        "housing",
        "accommodation",
        "halls",
        "residence",
        "rent",
        "landlord",
        "tenant",
    ],
    "industrial_action": [
        "industrial action",
        "strike",
        "union",
    ],
    "new_students": [
        "new student",
        "fresher",
        "induction",
        "welcome week",
        "orientation",
    ],
    "returning_to_study": [
        "returning to study",
        "interruption",
        "resuming",
        "coming back",
        "leave of absence",
    ],
    "student_life": [
        "student life",
        "society",
        "societies",
        "club",
        "sports",
        "events",
    ],
    "visas_immigration_and_support": [
        "visa",
        "immigration",
        "tier 4",
        "cas",
        "sponsor",
        "international student",
        "right to work",
    ],
    "other": [],
}
