# Generated by Django 6.0.2 on 2026-02-19 11:46

import django.contrib.auth.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import tickets.helpers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        max_length=30,
                        unique=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                message="Username must consist of @ followed by at least three alphanumericals",
                                regex="^@\\w{3,}$",
                            )
                        ],
                    ),
                ),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "user_type",
                    models.CharField(
                        choices=[("student", "Student"), ("staff", "Staff")],
                        default="student",
                        max_length=10,
                    ),
                ),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                (
                    "self_intro",
                    models.TextField(
                        blank=True, default="Hello! My friends!", max_length=200
                    ),
                ),
                (
                    "faculties",
                    models.TextField(
                        blank=True, help_text="Comma-separated faculty codes"
                    ),
                ),
                (
                    "study_levels",
                    models.TextField(
                        blank=True, help_text="Comma-separated study level codes"
                    ),
                ),
                (
                    "categories",
                    models.TextField(
                        blank=True, help_text="Comma-separated category codes"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "faculty",
                    models.CharField(
                        choices=[
                            ("", "Select"),
                            ("folsm", "Faculty of Life Sciences & Medicine (FoLSM)"),
                            (
                                "sspp",
                                "Faculty of Social Science & Public Policy (SSPP)",
                            ),
                            (
                                "nmpc",
                                "Florence Nightingale Faculty of Nursing, Midwifery & Palliative Care (NMPC)",
                            ),
                            (
                                "nmes",
                                "Faculty of Natural, Mathematical & Engineering Sciences (NMES)",
                            ),
                            ("ah", "Faculty of Arts & Humanities (A&H)"),
                            ("kbs", "King's Business School (KBS)"),
                            (
                                "docs",
                                "Faculty of Dentistry, Oral & Craniofacial Sciences (DOCS)",
                            ),
                            ("dpsol", "The Dickson Poon School of Law (DPSoL)"),
                            (
                                "ioppn",
                                "Institute of Psychiatry, Psychology & Neuroscience (IoPPN)",
                            ),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "study_level",
                    models.CharField(
                        choices=[
                            ("", "Select"),
                            ("undergraduate", "Undergraduate"),
                            ("postgraduate_taught", "Postgraduate Taught"),
                            ("postgraduate_research", "Postgraduate Research"),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("", "Select"),
                            ("assessment", "Assessment"),
                            ("welfare", "Welfare"),
                            ("careers", "Careers"),
                            ("financial_issues", "Financial Issues"),
                            (
                                "uni_procedures_regulations",
                                "University Procedures & Regulations",
                            ),
                            ("administration", "Administration"),
                            (
                                "appeals_complaints_and_misconduct",
                                "Appeals, Complaints & Misconduct",
                            ),
                            ("dignity_and_inclusion", "Dignity & Inclusion"),
                            ("disability_support", "Disability Support"),
                            (
                                "document_and_letter_requests",
                                "Document & Letter Requests",
                            ),
                            (
                                "fees_funding_and_money_advice",
                                "Fees, Funding & Money Advice",
                            ),
                            ("graduation", "Graduation"),
                            ("health_and_wellbeing", "Health & Wellbeing"),
                            (
                                "housing_and_accommodation_support",
                                "Housing & Accommodation Support",
                            ),
                            ("industrial_action", "Industrial Action"),
                            ("new_students", "New Students"),
                            ("returning_to_study", "Returning to Study"),
                            ("student_life", "Student Life"),
                            (
                                "visas_immigration_and_support",
                                "Visas, Immigration & Support",
                            ),
                            ("other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("subject", models.CharField(max_length=78)),
                (
                    "body",
                    models.TextField(
                        max_length=50000,
                        validators=[django.core.validators.MaxLengthValidator(50000)],
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="ticket_attachments/%Y/%m/%d/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "txt",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                ]
                            ),
                            tickets.helpers._validate_file_size,
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("awaiting_staff", "Awaiting staff"),
                            ("awaiting_student", "Awaiting student"),
                            ("closed", "Closed"),
                        ],
                        default="awaiting_staff",
                        max_length=32,
                    ),
                ),
                (
                    "closed_reason",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("answered", "Answered"),
                            ("inactivity", "Inactivity"),
                        ],
                        max_length=32,
                        null=True,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("pending priority", "Pending Priority"),
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                        ],
                        default="pending priority",
                        max_length=32,
                    ),
                ),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url_code", models.CharField(blank=True, max_length=64, unique=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"user_type": "staff"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        limit_choices_to={"user_type": "student"},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "body",
                    models.TextField(
                        max_length=5000,
                        validators=[django.core.validators.MaxLengthValidator(5000)],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="comments",
                        to="tickets.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
