# Generated by Django 5.2.7 on 2026-01-31 01:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_user_user_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty', models.CharField(choices=[('folsm', 'Faculty of Life Sciences & Medicine (FoLSM)'), ('sspp', 'Faculty of Social Science & Public Policy (SSPP)'), ('nmpc', 'Florence Nightingale Faculty of Nursing, Midwifery & Palliative Care (NMPC)'), ('nmes', 'Faculty of Natural, Mathematical & Engineering Sciences (NMES)'), ('ah', 'Faculty of Arts & Humanities (A&H)'), ('kbs', "King's Business School (KBS)"), ('docs', 'Faculty of Dentistry, Oral & Craniofacial Sciences (DOCS)'), ('dpsol', 'The Dickson Poon School of Law (DPSoL)'), ('ioppn', 'Institute of Psychiatry, Psychology & Neuroscience (IoPPN)')], max_length=64)),
                ('study_level', models.CharField(choices=[('undergraduate', 'Undergraduate'), ('postgraduate_taught', 'Postgraduate Taught'), ('postgraduate', 'Postgraduate')], max_length=64)),
                ('category', models.CharField(choices=[('assessment', 'Assessment'), ('welfare', 'Welfare'), ('health', 'Health'), ('careers', 'Careers'), ('financial_issues', 'Financial Issues'), ('uni_procedures_regulations', 'University Procedures and Regulations'), ('misconduct_allegations', 'Misconduct Allegations'), ('other', 'Other')], max_length=64)),
                ('subject', models.CharField(max_length=78)),
                ('body', models.TextField(max_length=50000)),
                ('status', models.CharField(choices=[('awaiting_staff', 'Awaiting staff'), ('awaiting_student', 'Awaiting student'), ('closed', 'Closed')], default='awaiting_staff', max_length=32)),
                ('closed_reason', models.CharField(blank=True, choices=[('answered', 'Answered'), ('inactivity', 'Inactivity')], max_length=32, null=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, limit_choices_to={'user_type': 'staff'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_tickets', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(limit_choices_to={'user_type': 'student'}, on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
