# Generated by Django 5.2.7 on 2026-01-31 02:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='body',
            field=models.TextField(max_length=50000, validators=[django.core.validators.MaxLengthValidator(50000)]),
        ),
    ]
