# Generated by Django 5.2.7 on 2026-02-03 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0004_alter_ticket_body"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="categories",
            field=models.TextField(
                blank=True, help_text="Comma-separated category codes"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="faculties",
            field=models.TextField(
                blank=True, help_text="Comma-separated faculty codes"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="profile_picture",
            field=models.ImageField(
                blank=True, null=True, upload_to="profile_pictures/"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="self_intro",
            field=models.TextField(
                blank=True, default="Hello! My friends!", max_length=200
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="study_levels",
            field=models.TextField(
                blank=True, help_text="Comma-separated study level codes"
            ),
        ),
    ]
