# Generated by Django 5.2.7 on 2026-02-09 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0005_alter_ticket_category_alter_ticket_faculty_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='faculty',
            field=models.CharField(choices=[('', 'Select'), ('folsm', 'Faculty of Life Sciences & Medicine (FoLSM)'), ('sspp', 'Faculty of Social Science & Public Policy (SSPP)'), ('nmpc', 'Florence Nightingale Faculty of Nursing, Midwifery & Palliative Care (NMPC)'), ('nmes', 'Faculty of Natural, Mathematical & Engineering Sciences (NMES)'), ('ah', 'Faculty of Arts & Humanities (A&H)'), ('kbs', "King's Business School (KBS)"), ('docs', 'Faculty of Dentistry, Oral & Craniofacial Sciences (DOCS)'), ('dpsol', 'The Dickson Poon School of Law (DPSoL)'), ('ioppn', 'Institute of Psychiatry, Psychology & Neuroscience (IoPPN)')], max_length=100),
        ),
    ]
