# Generated by Django 5.2.7 on 2026-02-09 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_alter_ticket_faculty'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('', 'Select'), ('assessment', 'Assessment'), ('welfare', 'Welfare'), ('careers', 'Careers'), ('financial_issues', 'Financial Issues'), ('uni_procedures_regulations', 'University Procedures & Regulations'), ('administration', 'Administration'), ('appeals_complaints_and_misconduct', 'Appeals, Complaints & Misconduct'), ('dignity_and_inclusion', 'Dignity & Inclusion'), ('disability_support', 'Disability Support'), ('document_and_letter_requests', 'Document & Letter Requests'), ('fees_funding_and_money_advice', 'Fees, Funding & Money Advice'), ('graduation', 'Graduation'), ('health_and_wellbeing', 'Health & Wellbeing'), ('housing_and_accommodation_support', 'Housing & Accommodation Support'), ('industrial_action', 'Industrial Action'), ('new_students', 'New Students'), ('returning_to_study', 'Returning to Study'), ('student_life', 'Student Life'), ('visas_immigration_and_support', 'Visas, Immigration & Support'), ('other', 'Other')], max_length=100),
        ),
        migrations.AlterField(
            model_name='ticket',
            name='study_level',
            field=models.CharField(choices=[('', 'Select'), ('undergraduate', 'Undergraduate'), ('postgraduate_taught', 'Postgraduate Taught'), ('postgraduate_research', 'Postgraduate Research'), ('other', 'Other')], max_length=100),
        ),
    ]
