# Generated by Django 5.2.7 on 2026-02-09 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0007_alter_ticket_category_alter_ticket_study_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='url_code',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
