# Generated by Django 5.2.7 on 2026-02-11 19:26

import django.core.validators
import tickets.models.ticket
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0008_ticket_url_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="attachment",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="ticket_attachments/%Y/%m/%d/",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=[
                            "pdf",
                            "doc",
                            "docx",
                            "txt",
                            "jpg",
                            "jpeg",
                            "png",
                        ]
                    ),
                    tickets.models.ticket.validate_file_size,
                ],
            ),
        ),
    ]
