# Generated by Django 5.2.7 on 2026-02-10 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0008_ticket_url_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("unassigned", "Unassigned"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                ],
                default="unassigned",
                max_length=32,
            ),
        ),
    ]
