# Generated by Django 5.2.7 on 2026-02-10 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0009_ticket_priority"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="priority",
            field=models.CharField(
                choices=[
                    ("pending priority", "Pending Priority"),
                    ("low", "Low"),
                    ("medium", "Medium"),
                    ("high", "High"),
                ],
                default="pending priority",
                max_length=32,
            ),
        ),
    ]
