# Generated by Django 5.2.7 on 2026-02-12 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_attachment'),
        ('tickets', '0010_alter_ticket_priority'),
    ]

    operations = [
    ]
