# Generated by Django 5.2.7 on 2026-02-12 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_comment'),
        ('tickets', '0011_merge_20260212_2228'),
    ]

    operations = [
    ]
