# Generated by Django 5.2.7 on 2026-02-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_merge_0009_comment_0011_merge_20260212_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='awaiting_student_since',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
