# Generated by Django 5.2.7 on 2026-02-26 00:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_ticket_awaiting_student_since'),
        ('tickets', '0013_ticketattachment'),
    ]

    operations = [
    ]
