# Generated by Django 5.2.7 on 2026-03-03 02:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_internalnote'),
        ('tickets', '0014_merge_20260226_0029'),
    ]

    operations = [
    ]
