# Generated by Django 5.2.7 on 2026-03-03 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_merge_20260226_0029'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='url_code',
            field=models.CharField(blank=True, max_length=64, unique=True),
        ),
    ]
