# Generated by Django 5.2.7 on 2026-03-03 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_comment_url_code'),
        ('tickets', '0015_merge_0014_internalnote_0014_merge_20260226_0029'),
    ]

    operations = [
    ]
