# Generated by Django 5.2.7 on 2026-03-12 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_merge_20260303_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='internal_notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.DeleteModel(
            name='InternalNote',
        ),
    ]
