# Generated by Django 5.2.7 on 2026-03-09 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0016_merge_20260303_1236"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="self_intro",
            field=models.TextField(blank=True, max_length=200),
        ),
    ]
