# Generated by Django 5.2.7 on 2026-03-14 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_user_self_intro'),
        ('tickets', '0017_ticket_internal_notes_delete_internalnote'),
    ]

    operations = [
    ]
