# Generated by Django 5.2.7 on 2026-03-11 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0017_issuegroup_ticket_issue_group"),
    ]

    operations = [
        migrations.AddField(
            model_name="issuegroup",
            name="slug",
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
