# Generated by Django 5.2.7 on 2026-03-12 07:09

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_merge_20260303_1236'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('folsm', 'Faculty of Life Sciences & Medicine (FoLSM)'), ('sspp', 'Faculty of Social Science & Public Policy (SSPP)'), ('nmpc', 'Florence Nightingale Faculty of Nursing, Midwifery & Palliative Care (NMPC)'), ('nmes', 'Faculty of Natural, Mathematical & Engineering Sciences (NMES)'), ('ah', 'Faculty of Arts & Humanities (A&H)'), ('kbs', "King's Business School (KBS)"), ('docs', 'Faculty of Dentistry, Oral & Craniofacial Sciences (DOCS)'), ('dpsol', 'The Dickson Poon School of Law (DPSoL)'), ('ioppn', 'Institute of Psychiatry, Psychology & Neuroscience (IoPPN)')], max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='preferred_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='pronouns',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, max_length=8, validators=[django.core.validators.RegexValidator(message='Student ID must be exactly 8 digits.', regex='^\\d{8}$')]),
        ),
        migrations.AddField(
            model_name='user',
            name='study_level',
            field=models.CharField(blank=True, choices=[('', 'Select'), ('undergraduate', 'Undergraduate'), ('postgraduate_taught', 'Postgraduate Taught'), ('postgraduate_research', 'Postgraduate Research'), ('other', 'Other')], max_length=100),
        ),
    ]
