# Generated by Django 5.2.7 on 2026-03-14 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_alter_user_self_intro'),
        ('tickets', '0018_user_student_fields'),
    ]

    operations = [
    ]
