# Generated by Django 5.2.7 on 2026-03-15 14:59

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0018_merge_20260314_1851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='internal_notes',
            field=models.TextField(blank=True, default='', max_length=50000, validators=[django.core.validators.MaxLengthValidator(50000)]),
        ),
    ]
