# Generated by Django 5.2.7 on 2026-03-13 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0018_issuegroup_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ticket",
            name="assigned_to",
        ),
        migrations.AddField(
            model_name="ticket",
            name="assigned_to",
            field=models.ManyToManyField(
                blank=True,
                limit_choices_to={"user_type": "staff"},
                related_name="assigned_tickets",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
