# Generated by Django 5.2.7 on 2026-03-16 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_alter_ticket_internal_notes'),
        ('tickets', '0019_merge_20260314_1713'),
    ]

    operations = [
    ]
