# Generated by Django 5.2.7 on 2026-03-16 03:21

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_merge_20260316_0024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='faculty',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='graduation_year',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(blank=True, default='', max_length=20, validators=[django.core.validators.RegexValidator(message='Phone number may only contain digits, spaces, and +()- characters.', regex='^[0-9+()\\-\\s]{7,20}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='preferred_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='pronouns',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='student_id',
            field=models.CharField(blank=True, default='', max_length=8, validators=[django.core.validators.RegexValidator(message='Student ID must be an 8 digit number.', regex='^\\d{8}$')]),
        ),
        migrations.AlterField(
            model_name='user',
            name='study_level',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
