# Generated by Django 5.2.7 on 2026-03-17 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0017_ticket_reminder_sent_at'),
        ('tickets', '0021_alter_user_faculty_alter_user_graduation_year_and_more'),
    ]

    operations = [
    ]
