# Generated by Django 5.2.7 on 2026-03-16 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0018_issuegroup_slug"),
        ("tickets", "0021_alter_user_faculty_alter_user_graduation_year_and_more"),
    ]

    operations = []
