# Generated by Django 5.2.7 on 2026-03-17 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0021_alter_user_faculty_alter_user_graduation_year_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(),
        ),
    ]
