# Generated by Django 5.2.7 on 2026-03-18 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0022_merge_20260316_2206'),
        ('tickets', '0022_merge_20260317_2330'),
    ]

    operations = [
    ]
