# Generated by Django 5.2.7 on 2026-03-19 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0022_alter_comment_body"),
        ("tickets", "0023_merge_20260318_1717"),
    ]

    operations = []
