# Generated by Django 5.2.7 on 2026-03-19 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0024_merge_20260319_1400"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="body",
            field=models.TextField(),
        ),
    ]
