# Generated by Django 5.2.7 on 2026-03-22 20:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tickets", "0024_merge_assigned_to_branch"),
        ("tickets", "0025_alter_ticket_body"),
    ]

    operations = []
