# Generated by Django 5.2.7 on 2026-03-23 03:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0025_merge_0024_issueupdate_0024_merge_assigned_to_branch'),
        ('tickets', '0026_merge_20260322_2003'),
    ]

    operations = [
    ]
