# Generated by Django 5.2.7 on 2026-03-24 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0027_merge_20260323_0333'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issueupdate',
            options={'ordering': ['-created_at', '-pk']},
        ),
    ]
