# Generated by Django 5.2.7 on 2026-03-31 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0028_alter_issueupdate_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='issueupdate',
            old_name='issue',
            new_name='issue_group',
        ),
    ]
